

### Test user creation
POST http://localhost:3000/api/user/ HTTP/1.1
content-type: application/json


{ 
    "user" : {
        "username": "daniel",
        "password": "pass"
    }
}

### Get user from authorization header
GET http://localhost:3000/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNjQ4YTllLTk1NDYtNGZiZC04NzIxLTU5YmZjNGY4ODVjNyIsImlhdCI6MTY1NjI1MzM1NywiZXhwIjoxNjU2MjU2OTU3fQ.owR9YE9A94mK_HdRMERNQiG7Pe8O-QPfvGX_bP7KDpc

### Get user from user Id

GET http://localhost:3000/api/user/81ffac03-c91e-4b7d-b10b-08c347433e81