/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_associativeecosystem_free(a: number): void;
export function associativeecosystem_get_cell_state(a: number, b: number, c: number): number;
export function associativeecosystem_get_previous_cell_state(a: number, b: number, c: number): number;
export function associativeecosystem_kill(a: number, b: number, c: number): void;
export function associativeecosystem_bless(a: number, b: number, c: number): void;
export function associativeecosystem_toggle(a: number, b: number, c: number): void;
export function associativeecosystem_tick(a: number): void;
export function associativeecosystem_get_relevant_cells(a: number): number;
export function associativeecosystem_get_relevant_cells_length(a: number): number;
export function associativeecosystem_new(): number;
export function __wbg_ecosystem_free(a: number): void;
export function ecosystem_bless(a: number, b: number, c: number): void;
export function ecosystem_kill(a: number, b: number, c: number): void;
export function ecosystem_toggle(a: number, b: number, c: number): void;
export function ecosystem_get_cell_state(a: number, b: number, c: number): number;
export function ecosystem_get_previous_cell_state(a: number, b: number, c: number): number;
export function ecosystem_tick(a: number): void;
export function ecosystem_new(a: number, b: number): number;
export function __wbg_iterator_free(a: number): void;
export function iterator_is_empty(a: number): number;
export function iterator_next(a: number): void;
export function iterator_reset(a: number): void;
export function iterator_get_current_row(a: number): number;
export function iterator_get_current_column(a: number): number;
export function iterator_new(): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
